# This file configures the analyzer for Dart.
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
